apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: guacamole
  name: guacamole-read-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guacamole-read-binding
  namespace: guacamole
subjects:
- kind: ServiceAccount
  name: guacamole-sa
  namespace: guacamole
roleRef:
  kind: Role
  name: guacamole-read-role
  apiGroup: rbac.authorization.k8s.io
